// Generated by hand to match supabase/migrations/20260622140000_create_wishlists_and_items.sql.
// Once the Supabase CLI is linked to the project, regenerate with:
// npx supabase gen types typescript --linked > lib/supabase/database.types.ts
export type Database = {
  public: {
    Tables: {
      wishlists: {
        Row: {
          id: string;
          owner_id: string;
          title: string;
          description: string | null;
          share_slug: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          title: string;
          description?: string | null;
          share_slug?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          title?: string;
          description?: string | null;
          share_slug?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      items: {
        Row: {
          id: string;
          wishlist_id: string;
          title: string;
          merchant_url: string | null;
          price: number | null;
          image_url: string | null;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          wishlist_id: string;
          title: string;
          merchant_url?: string | null;
          price?: number | null;
          image_url?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          wishlist_id?: string;
          title?: string;
          merchant_url?: string | null;
          price?: number | null;
          image_url?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "items_wishlist_id_fkey";
            columns: ["wishlist_id"];
            isOneToOne: false;
            referencedRelation: "wishlists";
            referencedColumns: ["id"];
          },
        ];
      };
      purchases: {
        Row: {
          id: string;
          item_id: string;
          purchased_by_name: string | null;
          purchased_by_user_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          item_id: string;
          purchased_by_name?: string | null;
          purchased_by_user_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          item_id?: string;
          purchased_by_name?: string | null;
          purchased_by_user_id?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "purchases_item_id_fkey";
            columns: ["item_id"];
            isOneToOne: true;
            referencedRelation: "items";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "purchases_purchased_by_user_id_fkey";
            columns: ["purchased_by_user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
